# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "my-telegram-bot"

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
region = "us-east-1"
disable_rollback = false
image_repositories = []
resolve_s3 = true
s3_prefix = "my-telegram-bot"
confirm_changeset = true
