version: "3"

services:
  create_lambda_zip:
    image: create_lambda_layer_zip:1.0
    container_name: create_lambda_layer_zip
    build:
      context: .
    
    ports:
      - 8556:8556

    volumes:
      - type: bind
        source: ./
        target: /src
