name: Formatting python code with yapf

on: [push]

jobs:
  static:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run YAPF to test if python code is correctly formatted
      uses: AlexanderMelde/yapf-action@master
      with:
        args: --style pep8 --no-local-style --verbose --recursive --diff --parallel
    - name: Run flake8 to check for static errors
      uses: py-actions/flake8@v2
      with: 
        path: "src"

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install pytest==7.4.2 pytest-md==0.2.0 python-telegram-bot==20.5 requests==2.31.0
    - name: Run unit tests
      run: |
        export BOT_TOKEN=${{ secrets.BOT_TOKEN }}
        pytest ./tests/unit/